# mock source code generated by defined interface
mockgen:
	mockgen -source testcase/test/interface.go -package mockinterfce -destination=testcase/test/mockgen/mockinterface.go
	mockgen -source testcase/db/interface.go -package mockdb -destination=testcase/db/mockgen/mockdb.go

# run main
run_main:
	go run main.go

# build main
build_main:
	go build main.go